# Generated by Django 3.2.6 on 2021-08-04 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='data_Evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(default=1, verbose_name='Data do evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
